" akk!... see http://wehavenoproduct.com/~cayla/.vimrc.html

" modeline examples:
" vi:noai:sw=3 ts=6
" /* vim: set ai tw=75: */


" set noexpandtab
" set softtabstop=4
" set tabstop=8
" set shiftwidth=4
" set foldmethod=indent 

set ts=4
