#!/bin/bash -e

#LN_FLAGS=${LN_FLAGS:--f}

if ! type realpath 2>/dev/null; then
	echo "realpath not found: try sudo apt-get install realpath" 1>&2;
	exit 1
fi


ROOT=$(dirname $(dirname $(realpath "$0")))
REL_ROOT=${ROOT#$HOME/}
cd $HOME

if ! [ -d "$REL_ROOT" ]; then
	echo '$REL_ROOT ($ROOT) not found; no changes' 1>&2
	exit 1
fi

find ${REL_ROOT}/etc -mindepth 1 -maxdepth 1 \! -name *~ \
| sort \
| while read f; do
	t=".$(basename "$f")"
	ln -bfnsv "$f" "$t"
done
