#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import, division, print_function, unicode_literals

"""
"Install" specified files by symlinking them, rooting at the user's home directory
"""

import logging
import os
import sys

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def install(p):
    """create a symlink from ~/ to <p>. A dot is always prepended if
    the p does not already begin with one. If p is a relative path,
    intermediate directories are created as necessary and the relative
    symlink target is updated appropriately. For example,
    install('opt/reece-desktop/etc-deep/.config/libreoffice/4/user/config/standard.soc')
    will create .config/libreoffice/4/user/config/standard.soc
    with target ../../../../../opt/reece-desktop/etc-deep/.config/libreoffice/4/user/config/standard.soc

    """

    


if __name__ == "__main__":
    args = sys.argv[1:]

    if any(not p.startswith('/') for p in args):
        raise RuntimeError("All args must be relative paths")

    # change to home directory
    os.chdir(os.path.abspath(os.path.expanduser('~')))

    for p in args:
        install(p)
