#!/bin/bash -e

#LN_FLAGS=${LN_FLAGS:--f}

ROOT=$(dirname $(dirname $(readlink -f "$0")))
REL_ROOT=${ROOT#$HOME/}
cd $HOME

if ! [ -d "$REL_ROOT" ]; then
	echo '$REL_ROOT ($ROOT) not found; no changes' 1>&2
	exit 1
fi

find ${REL_ROOT}/etc -mindepth 1 -maxdepth 1 \! -name *~ \
| sort \
| while read f; do
	t=".$(basename "$f")"
	if [ -h "$t" -a "$(readlink "$t")" = "$f" ]; then
		continue
	fi
	ln -bfnsv "$f" "$t"
done
